### ISSUE TITLE
Add `-> None` to `Nav.__init__()`

### ISSUE THREAD

**Issue by peterschutt** [oprypin/mkdocs-gen-files#19]
Hi, thanks for this really useful library!

I get an error from mypy when using `Nav`:

> docs/gen_ref_pages.py:10: error: Call to untyped function "Nav" in typed context  [no-untyped-call]

It is due to the fact that an `__init__()` method with no args and no return type is considered untyped.

Would you accept a PR adding `-> None:` for the method.

Cheers!

**Comment by oprypin** [comment]
OK. But this seems like a totally unreasonable lint check. It just shouldn't be used and shouldn't be a thing. Just stick to no-untyped-def if you want to be pedantic with your own code

**Comment by peterschutt** [comment]
I already have a # type:ignore[...] there for it. I don't want to make a change that you don't support.
