### ISSUE TITLE
Generate index.md warning

### ISSUE THREAD

**Issue by zhangnew** [oprypin/mkdocs-gen-files#24]
I want to use this plugin to generate a table of contents for my documentation, but I get the following warning:
> WARNING  -  Documentation file 'index.md' contains a link to 'xx/index.html' which is not found in the documentation files.
 
Is it possible to change the timing of the plugin execution to eliminate this kind of warning?

**Comment by oprypin** [comment]
You need to link to  index.md, not index.html

**Comment by zhangnew** [comment]
Thx !
