### ISSUE TITLE
`mkdocs-awesome-pages` doesn't jive with generated docs

### ISSUE THREAD

**Issue by thejcannon** [oprypin/mkdocs-gen-files#28]
:wave: Loving the plugin!

I filed https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/78 against that repo, so I'll file one here too.

Essentially, generated pages (and navs) don't work well together.

**Comment by oprypin** [comment]
I think you found the answer why this happens on the other issue.

Meanwhile my self-endorsed solution is to use mkdocs-literate-nav instead :D
* https://oprypin.github.io/mkdocs-gen-files/extras.html#programmatically-generating-the-navigation
* https://mkdocstrings.github.io/recipes/#generate-a-literate-navigation-file
