### ISSUE TITLE
Scripts relative to mkdocs.yml file?

### ISSUE THREAD

**Issue by rudolfbyker** [oprypin/mkdocs-gen-files#5]
It would be great to be able to specify scripts relative to the mkdocs.yml file.

## Use case

In my `mkdocs.yml` file:

```yaml
plugins:
  - gen-files:
      scripts:
        - gen_pages.py
```

If the current working directory is the folder containing `mkdocs.yml`, this works:

```
mkdocs build
```

But if I want to run this from somewhere else, this does not work:

```
mkdocs build -f /absolute/path/to/mkdocs.yml
```

This is very cumbersome for all kinds of CI/CD situations. It would be nice for mkdocs-gen-files to be consistent with the rest of the ecosystem, where everything is relative to the `mkdocs.yml` file.

**Comment by oprypin** [comment]
Opened PR
* #17
